<?php
$this->adminPageTitleBar('更新密码');


$data->form->get('old_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '请输入现在的密码',
]);

$data->form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '设置一个新密码',
]);

$data->form->get('re_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => '再输入一次新密码',
]);

$data->form->get('submit')->setAttributes(['class'=>'btn btn-primary', 'value' => '更新密码']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-md-6">

        <p>密码修改完成后, 请牢记新密码, 在下次登录将启用新密码登入.</p>

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get('csrf')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get('old_password'), '当前密码'); ?>
            <?php echo $this->formElement($data->form->get('old_password')); ?>
            <?php echo $this->formElementErrors($data->form->get('old_password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get('new_password'), '新密码'); ?>
            <?php echo $this->formElement($data->form->get('new_password')); ?>
            <?php echo $this->formElementErrors($data->form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get('re_new_password'), '确认新密码'); ?>
            <?php echo $this->formElement($data->form->get('re_new_password')); ?>
            <?php echo $this->formElementErrors($data->form->get('re_new_password')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get('submit')); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

