<?php

$this->pageTitleBar('更新我的资料');


$data->form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => $data->adminer->getAdminName(),
]);

$data->form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>

<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get('csrf')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get('name'), '更新名字'); ?>
            <?php echo $this->formElement($data->form->get('name')); ?>
            <?php echo $this->formElementErrors($data->form->get('name')); ?>

        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get('submit')); ?>

        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>

