<?php
use Admin\Form\GroupForm;

$this->adminPageTitleBar('修改分组信息');
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$data->form->get(GroupForm::FIELD_NAME)->setAttributes([
    'class' => 'form-control',
    'value' => $data->group->getGroupName(),
    'placeholder' => '输入分组名称'
]);

$data->form->get(GroupForm::FIELD_DESC)->setAttributes([
    'class' => 'form-control',
    'value' => $data->group->getGroupDesc(),
]);


$data->form->get(GroupForm::FIELD_SUBMIT)->setAttributes(['class'=>'btn btn-primary']);

$data->form->prepare();

?>


<div class="row">
    <div class="col-lg-6">

        <?php echo $this->form()->openTag($data->form); ?>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(GroupForm::FIELD_CSRF)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(GroupForm::FIELD_NAME), '分组名称'); ?>
            <?php echo $this->formElement($data->form->get(GroupForm::FIELD_NAME)); ?>
            <?php echo $this->formElementErrors($data->form->get(GroupForm::FIELD_NAME)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formLabel($data->form->get(GroupForm::FIELD_DESC), '分组简介'); ?>
            <?php echo $this->formElement($data->form->get(GroupForm::FIELD_DESC)); ?>
            <?php echo $this->formElementErrors($data->form->get(GroupForm::FIELD_DESC)); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formElement($data->form->get(GroupForm::FIELD_SUBMIT)); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>
