<?php
use Admin\Entity\Group;

$this->adminPageTitleBar('分组列表');
$this->adminSideTreeMenu()->setActiveID($data->activeID);

?>

    <div class="row">
        <div class="col-lg-12">
            <p>
                <a class="btn btn-default" href="<?php echo $this->url('admin/group', ['action' => 'add']); ?>"><i
                            class="fa fa-plus fa-fw"></i> 新增分组</a>
            </p>

            <table class="table table-striped">
                <tr>
                    <th>No</th>
                    <th>分组名称</th>
                    <th>创建时间</th>
                    <th>操作</th>
                </tr>

                <?php $i = 1; foreach ($data->groups as $group) { if(!$group instanceof Group) { continue; } ?>

                    <tr>
                        <td><?php echo $i++; ?></td>
                        <td><?php echo $group->getGroupName(); ?></td>
                        <td><?php echo $group->getGroupCreated()->format('Y-m-d H:i:s'); ?></td>
                        <td>
                            <ul class="nav nav-pills actions-list" role="tablist">
                                <li role="presentation" class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        操作选项 <span class="caret"></span>
                                    </a>

                                    <?php if(Group::DEFAULT_GROUP != $group->getGroupDefault()) { ?>

                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="<?php echo $this->url('admin/group', ['action' => 'edit', 'key' => $group->getGroupID()]); ?>">
                                                <i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> 修改信息
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/group', ['action' => 'delete', 'key' => $group->getGroupID()]); ?>">
                                                <i class="fa fa-times fa-fw" aria-hidden="true"></i> 删除分组
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="<?php echo $this->url('admin/group', ['action' => 'adminer', 'key' => $group->getGroupID()]); ?>">
                                                <i class="fa fa-users fa-fw" aria-hidden="true"></i> 分组成员配置
                                            </a>
                                        </li>
                                    </ul>


                                    <?php } ?>

                                </li>
                            </ul>
                        </td>
                    </tr>

                <?php } ?>

            </table>

        </div>
    </div>

<?php echo $this->pagination()->render(); ?>