<?php

if (!$data->adminer instanceof \Admin\Entity\Adminer) {
    throw new RuntimeException('Invalid administrator information');
}

$this->adminPageTitleBar('管理员分组配置', $data->adminer->getAdminName());
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$joined = $data->adminer->getAdminGroups();

?>


<div class="row">
    <div class="col-lg-12">
        <form method="post">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">已加入的分组</h3>
                </div>
                <div class="panel-body">
                    <?php
                    foreach($joined as $group) {
                        if(!$group instanceof \Admin\Entity\Group) { continue; }
                        $isDefault = \Admin\Entity\Group::DEFAULT_GROUP == $group->getGroupDefault();
                    ?>
                    <label class="btn btn-default<?php echo $isDefault ? ' disabled' : ''; ?>" style="margin: 5px; 0;">
                        <input
                            name="joined[]"
                            type="checkbox"
                            checked="checked"
                            <?php echo $isDefault ? ' onclick="return false;" ' : ''; ?>
                            value="<?php echo $group->getGroupID(); ?>"
                        > <?php echo $group->getGroupName(); ?>
                    </label>
                    <?php } ?>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">未加入的分组</h3>
                </div>
                <div class="panel-body">
                    <?php
                    foreach($data->groups as $group) {
                        if(!$group instanceof \Admin\Entity\Group) { continue; }
                        if ($joined->contains($group)) { continue; }
                    ?>
                    <label class="btn btn-default" style="margin: 5px; 0;">
                        <input
                            name="unjoin[]"
                            type="checkbox"
                            value="<?php echo $group->getGroupID(); ?>"
                        > <?php echo $group->getGroupName(); ?>
                    </label>
                    <?php } ?>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保存配置">
            </div>
        </form>
    </div>
</div>
