<?php

$this->adminPageTitleBar('管理员权限配置', '管理员列表');

//$this->adminSideTreeMenu()->setActiveID($activeID);

?>

    <div class="row">
        <div class="col-lg-12">
            <table class="table table-hover">
                <tr>
                    <th>管理员名称</th>
                    <th>管理员账号</th>
                    <th>管理员等级</th>
                    <th>管理员账号失效时间</th>
                    <th>权限配置</th>
                </tr>
                <?php
                foreach ($data->adminers as $adminer) {
                    if (! $adminer instanceof \Admin\Entity\Adminer) { continue; }
                    ?>

                    <tr>
                        <td height="60"><?php echo $adminer->getAdminName(); ?></td>
                        <td><?php echo $adminer->getAdminEmail(); ?></td>
                        <td><?php echo $adminer->getAdminLevelAsString(); ?></td>
                        <td><?php echo $adminer->getAdminExpired()->format('Y-m-d'); ?></td>
                        <?php if(\Admin\Entity\Adminer::DEFAULT_ADMIN == $adminer->getAdminDefault()) { ?>
                            <td>默认管理员权限配置</td>
                        <?php } else { ?>
                            <td>
                                <a href="<?php echo $this->url('admin/acl', ['action' => 'admineracl', 'key' => $adminer->getAdminID()]); ?>">查看管理员权限配置</a>
                            </td>
                        <?php } ?>
                    </tr>
                <?php } ?>

            </table>
        </div>
    </div>

<?php echo $this->pagination()->render(); ?>