<?php

if (! $data->group instanceof \Admin\Entity\Group) {
    throw new \Admin\Exception\RuntimeException('Need a group object.');
}

$this->adminPageTitleBar('分组权限配置', '分组权限: ' . $data->group->getGroupName());
$this->adminSideTreeMenu()->setActiveID($data->activeID);

$this->inlineScript()->captureStart();
echo <<<JS

$(function () {
    
    $(".action-status").change(function () {
        var aclUrl = $("#aclApi").val();
        var actionID = $(this).attr("name");
        var status = $(this).val();
        
        $.ajax({
            url: aclUrl,
            async: true,
            cache: false,
            global: false,
            type: 'POST',
            data: {'action_id':actionID, 'status': status},
            dataType: 'json',
            complete: function(jqXHR, textStatus) {
                
            },
            error: function(jqXHR, textStatus, errorThrown) {
                alert('删除失败, 请重新再试!');
                location.reload(true);
            },
            success: function(data, textStatus, jqXHR) {
            
            }
        });
    });
});

JS;
$this->inlineScript()->captureEnd();

?>

<div class="row">
    <input id="aclApi" type="hidden" value="<?php echo $this->url('admin/acl', ['action' => 'acl', 'key' => $data->group->getGroupID()]); ?>">
    <?php
    $allowedActions = $data->group->getGroupActions();
    foreach ($data->components as $component) {
        if (! $component instanceof \Admin\Entity\Component) { continue; }
    ?>
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-<?php echo $component->getComponentIcon(); ?> fa-fw"></i>
                    <?php echo $component->getComponentName(); ?>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <?php
                        $actions = $component->getComponentActions();
                        foreach ($actions as $action) {
                            $actionID = $action->getActionID();
                        ?>
                            <tr>
                                <td>
                                    <i class="fa fa-<?php echo $action->getActionIcon(); ?> fa-fw"></i>
                                    <?php echo $action->getActionName(); ?>
                                </td>
                                <td class="text-right">
                                    <select name="<?php echo $actionID; ?>" class="action-status">
                                        <?php if($allowedActions->contains($action)) { ?>
                                            <option value="allow" selected>允许访问</option>
                                            <option value="deny">禁止访问</option>
                                        <?php } else { ?>
                                            <option value="allow">允许访问</option>
                                            <option value="deny" selected>禁止访问</option>
                                        <?php } ?>
                                    </select>
                                </td>
                            </tr>
                        <?php }  ?>
                    </table>
                </div>
            </div>
        </div>
    <?php } ?>

</div>
<?php echo $this->pagination()->render(); ?>
