<?php


if (! $data->group instanceof \Admin\Entity\Group) {
    throw new \Admin\Exception\RuntimeException('Need a group object.');
}

$this->adminPageTitleBar('分组权限配置', '分组权限: ' . $data->group->getGroupName());

//$this->adminSideTreeMenu()->setActiveID($activeID);

$this->inlineScript()->captureStart();
echo <<<JS

$(function () {
    
    $(".action-status").change(function () {
        var aclUrl = $("#aclApi").val();
        var actionID = $(this).attr("name");
        var status = $(this).val();
        alert(aclUrl);
        alert(actionID);
        alert(status);
        //$(this).blur();
        //$.get(url, function (dt) {
            //if(!dt.success) {
                //alert('System error!' + "\\n" + dt.message);
            //}
        //}, 'json');
    });
});

JS;
$this->inlineScript()->captureEnd();

?>

<div class="row">
    <input id="aclApi" type="hidden" value="<?php echo $this->url('admin/acl', ['action' => 'groupacled', 'key' => $data->group->getGroupID()]); ?>">
    <?php
    $allowedActions = $data->group->getGroupActions();
    foreach ($data->components as $component) {
        if (! $component instanceof \Admin\Entity\Component) { continue; }
    ?>
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-<?php echo $component->getComponentIcon(); ?> fa-fw"></i>
                    <?php echo $component->getComponentName(); ?>
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <?php
                        $actions = $component->getComponentActions();
                        foreach ($actions as $action) {
                            $actionID = $action->getActionID();
                        ?>
                            <tr>
                                <td>
                                    <i class="fa fa-<?php echo $action->getActionIcon(); ?> fa-fw"></i>
                                    <?php echo $action->getActionName(); ?>
                                </td>
                                <td class="text-right">
                                    <select name="<?php echo $actionID; ?>" class="action-status">
                                        <?php if($allowedActions->contains($action)) { ?>
                                            <option value="allow" selected>允许访问</option>
                                            <option value="deny">禁止访问</option>
                                        <?php } else { ?>
                                            <option value="allow">允许访问</option>
                                            <option value="deny" selected>禁止访问</option>
                                        <?php } ?>
                                    </select>
                                </td>
                            </tr>
                        <?php }  ?>
                    </table>
                </div>
            </div>
        </div>
    <?php } ?>

</div>
<?php echo $this->pagination()->render(); ?>
