<?php

$this->adminPageTitleBar('权限配置', '分组列表');
$this->adminSideTreeMenu()->setActiveID($data->activeID);

?>

    <div class="row">
        <div class="col-lg-12">
            <table class="table table-hover">
                <tr>
                    <th>部门名称</th>
                    <th>创建时间</th>
                    <th>成员人数</th>
                    <th>权限配置</th>
                </tr>
                <?php
                foreach ($data->groups as $group) {
                    if (! $group instanceof \Admin\Entity\Group) { continue; }
                ?>

                    <tr>
                        <td height="60"><?php echo $group->getGroupName(); ?></td>
                        <td><?php echo $group->getGroupCreated()->format('Y-m-d'); ?></td>
                        <td><strong><?php echo $group->getGroupAdminers()->count(); ?></strong> 人</td>
                        <?php if(\Admin\Entity\Group::DEFAULT_GROUP == $group->getGroupDefault()) { ?>
                            <td>默认分组权限配置</td>
                        <?php } else { ?>
                        <td>
                            <a href="<?php echo $this->url('admin/acl', ['action' => 'group', 'key' => $group->getGroupID()]); ?>">查看分组权限配置</a>
                        </td>
                        <?php } ?>
                    </tr>
                <?php } ?>

            </table>
        </div>
    </div>

<?php echo $this->pagination()->render(); ?>